services:
  analitex-app:
    image: ${IMAGE_TAG}
    container_name: analitex-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:${CONTAINER_PORT:-3000}"
    networks:
      - apps-proxy

networks:
  apps-proxy:
    external: true
